package rm1.rules;

import my.drools.templates.facts.FactOne;
import my.drools.templates.facts.RuleResponse;

global RuleResponse response;

dialect "mvel"

rule "Rule Four :: GGG"
    when
        FactOne($value:parameterName, parameterName!=null)
        Boolean(booleanValue==true) from $value.contains("GGG")
    then
        response.setResult(true);
        System.out.println("Invalid @{parameter}");
end